version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://user:password@db/ecommerce_db"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  db_data: